"""Set donations donor_id foreign key to nullable true for public donors

Revision ID: 05e6b6bfdf84
Revises: 394891ae17b7
Create Date: 2025-05-07 15:49:12.050173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e6b6bfdf84'
down_revision = '394891ae17b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donations', 'donor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donations', 'donor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
