"""Put beneficiary name to be nullable in STory table.

Revision ID: 076f0d7c6933
Revises: 1473daed9dea
Create Date: 2025-05-05 10:33:44.622894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076f0d7c6933'
down_revision = '1473daed9dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               postgresql_using="quantity::integer",
               existing_nullable=False)

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.alter_column('beneficiary_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.alter_column('beneficiary_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
