"""Changed created_at to date in story model

Revision ID: 0e07e1661525
Revises: 05e6b6bfdf84
Create Date: 2025-05-09 12:45:08.671664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e07e1661525'
down_revision = '05e6b6bfdf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('stories', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('stories', 'date')
    # ### end Alembic commands ###
