"""Add user_id foreign key to Donor

Revision ID: 1473daed9dea
Revises: 802b5da6587b
Create Date: 2025-05-04 15:15:42.238231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1473daed9dea'
down_revision = '802b5da6587b'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('donors', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
#         batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

def upgrade():
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))  # Or nullable=True if needed
        batch_op.create_foreign_key('fk_donors_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
