"""Changed donor model

Revision ID: 339a186e0f9f
Revises: d6ed06880539
Create Date: 2025-05-03 20:49:12.685136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339a186e0f9f'
down_revision = 'd6ed06880539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
