"""Put contact in user model

Revision ID: 36fcc1c9c3fa
Revises: 339a186e0f9f
Create Date: 2025-05-03 21:48:19.009723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fcc1c9c3fa'
down_revision = '339a186e0f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('users', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('contact', sa.String(length=200), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
