"""Added frequency to donation model

Revision ID: 394891ae17b7
Revises: 1b1151f6cec4
Create Date: 2025-05-06 12:29:29.389686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394891ae17b7'
down_revision = '1b1151f6cec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('frequency', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'frequency')
    # ### end Alembic commands ###
