"""Added donor and charity user creation upon user registration

Revision ID: 40c3b3cfd742
Revises: eb9f5cd651f6
Create Date: 2025-05-06 10:38:56.855117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c3b3cfd742'
down_revision = 'eb9f5cd651f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charities', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('donors', sa.Column('profile_pic', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donors', 'profile_pic')
    op.drop_column('charities', 'password_hash')
    # ### end Alembic commands ###
