"""Put full_name in user model

Revision ID: 802b5da6587b
Revises: 36fcc1c9c3fa
Create Date: 2025-05-03 21:54:25.780746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802b5da6587b'
down_revision = '36fcc1c9c3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
