"""Put one to many beneficiary and inventory relationship

Revision ID: a4e7cfd6762a
Revises: c166b31028a9
Create Date: 2025-05-05 19:25:03.765130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e7cfd6762a'
down_revision = 'c166b31028a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('beneficiary_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory', 'beneficiary', ['beneficiary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'beneficiary_id')
    # ### end Alembic commands ###
