"""fixing the database

Revision ID: a9dd58c88ecf
Revises: a940a33b5b29
Create Date: 2025-05-04 13:21:31.862266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9dd58c88ecf'
down_revision = 'a940a33b5b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
