"""Updated inventory model

Revision ID: ac91b935a912
Revises: 6348407cfdac
Create Date: 2025-05-04 18:34:19.635014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac91b935a912'
down_revision = '6348407cfdac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'inventory',
        'quantity',
        existing_type=sa.String(length=100),
        type_=sa.Integer(),
        postgresql_using="quantity::integer"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
