"""Add created_at to stories

Revision ID: c4a390c32ad4
Revises: 0e07e1661525
Create Date: 2025-05-09 21:51:55.743825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4a390c32ad4'
down_revision = '0e07e1661525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('stories', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('stories', 'created_at')
    # ### end Alembic commands ###
