"""Fix foreign key reference

Revision ID: ddf2e30ec87c
Revises: 
Create Date: 2025-04-30 23:06:07.978362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddf2e30ec87c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('repeat_donation', sa.Boolean(), nullable=True),
    sa.Column('reminder_set', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('donation')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'charities', ['charity_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        # Adding the role column with a default value to prevent null errors
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False, server_default='user'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('role')

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('charity_id')

    op.create_table('donation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('donor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('charity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('anonymous', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('repeat_donation', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reminder_set', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name='donation_charity_id_fkey'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], name='donation_donor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='donation_pkey')
    )
    op.drop_table('donations')
    # ### end Alembic commands ###
