"""Reset migrations

Revision ID: de0b5063d24b
Revises: 
Create Date: 2025-05-06 16:42:32.690753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0b5063d24b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Charities
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # Donations
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(length=20), nullable=False))

    # Donors
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=20), nullable=True))

    # Inventory - add nullable column first
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beneficiary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'beneficiary', ['beneficiary_id'], ['id'])

    # Backfill data for existing rows
    # op.execute("UPDATE inventory SET beneficiary_id = 1 WHERE beneficiary_id IS NULL")

    # Now alter the column to be non-nullable
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('beneficiary_id', nullable=False)

    # Stories
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('beneficiary_name',
            existing_type=sa.VARCHAR(length=100),
            nullable=True)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.alter_column('beneficiary_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('beneficiary_id')

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
