"""Added serialization to inventory model

Revision ID: eb9f5cd651f6
Revises: a4e7cfd6762a
Create Date: 2025-05-06 00:33:45.565398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9f5cd651f6'
down_revision = 'a4e7cfd6762a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'beneficiary_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'beneficiary_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
