"""recreate migrations

Revision ID: ed2b126fc3ed
Revises: 05e6b6bfdf84
Create Date: 2025-05-09 11:39:05.107851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2b126fc3ed'
down_revision = '05e6b6bfdf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
